# Generated by Django 5.0.4 on 2024-04-25 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Account',
            fields=[
                ('adminName', models.CharField(max_length=30)),
                ('adminPassword', models.CharField(max_length=30)),
                ('adminEmail', models.CharField(max_length=50)),
                ('accountID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipmentName', models.CharField(max_length=30)),
                ('equipmentType', models.CharField(max_length=30)),
                ('equipmentAssests', models.CharField(max_length=30)),
                ('equipmentStatus', models.CharField(max_length=30)),
                ('equipmentWarranty', models.CharField(max_length=30)),
                ('equipmentOnSite', models.BooleanField()),
                ('equipmentAudit', models.CharField(max_length=30)),
                ('equipmentID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('userName', models.CharField(max_length=30)),
                ('userPassword', models.CharField(max_length=30)),
                ('userEmail', models.CharField(max_length=50)),
                ('accountID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.admin_account')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('startDate', models.CharField(max_length=10)),
                ('endDate', models.CharField(max_length=10)),
                ('bookingStatus', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('L', 'Late')], max_length=10)),
                ('bookingID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('accountID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.user_account')),
                ('equipmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.equipment')),
            ],
        ),
    ]
