# Generated by Django 5.0.4 on 2024-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipmentAssests',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipmentOnSite',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipmentWarranty',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipmentLocation',
            field=models.CharField(choices=[('XRLBC', 'XRL Lab Blue Cabinet'), ('XRLBCL', 'XRL Lab Blue Cabinet Large'), ('XRL', 'XRL Lab'), ('OTHER', 'Other'), ('XRLMWC', 'XRLab Medium Wooden Cabinet')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipmentQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentAudit',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipmentStatus',
            field=models.CharField(choices=[('A', 'Available'), ('ON', 'On Loan'), ('D', 'Decommissioned'), ('R', 'Repairing')], default='A', max_length=20),
        ),
    ]
