# Generated by Django 5.0.4 on 2024-04-26 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_remove_equipment_equipmentassests_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='equipmentID',
            new_name='equipment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='accountID',
        ),
        migrations.AddField(
            model_name='booking',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
