# Generated by Django 5.0.4 on 2024-04-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_rename_equipmentid_booking_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='userFK',
        ),
        migrations.DeleteModel(
            name='Admin_Account',
        ),
        migrations.DeleteModel(
            name='User_Account',
        ),
    ]
