# Generated by Django 5.0.4 on 2024-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_remove_user_account_userfk_delete_admin_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
