# Generated by Django 5.0.4 on 2024-04-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_remove_booking_bookingid_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='bookingID',
        ),
    ]
