# Generated by Django 5.0.4 on 2024-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_rename_id_booking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateField(),
        ),
    ]
