# Generated by Django 5.0.4 on 2024-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_alter_booking_enddate_alter_booking_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipmentComment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
